package com.zelenux.upprpo_server_test.observed.exceptions;

public class AlreadyExistsException extends Exception {
}
